name: Test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          sudo apt-get update && sudo apt-get install -y python3-dnspython graphviz
          python3 setup.py build && sudo python3 setup.py install
      - name: test
        run: |
          (
          for a in $(
            find dnsviz/analysis \
            -name '*.py' \
            \! -name '__init__.py' \
            \! -name 'status.py' \
            \! -name 'offline.py'
          ); do
            echo
            echo $a:
            python3 -m doctest -o ELLIPSIS $a 2>&1
          done
          ) >> "$GITHUB_STEP_SUMMARY"
